package com.mx.ymate.security;

/**
 * @Author: mengxiang.
 * @Date 2025/04/24.
 * @Time: 11:00.
 * @Description: 安全模块验证常量
 */
public interface ValidateConstant {

    String USER_NAME_NOT_EMPTY_MSG = "用户名不能为空";
    String USER_NAME_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.USER_NAME_NOT_EMPTY";
    String REAL_NAME_NOT_EMPTY_MSG = "真实姓名不能为空";
    String REAL_NAME_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.REAL_NAME_NOT_EMPTY";
    String MOBILE_NOT_EMPTY_MSG = "手机号不能为空";
    String MOBILE_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.MOBILE_NOT_EMPTY";
    String GENDER_NOT_EMPTY_MSG = "性别不能为空";
    String GENDER_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.GENDER_NOT_EMPTY";
    String PARENT_ID_NOT_EMPTY_MSG = "父ID不能为空";
    String PARENT_ID_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.PARENT_ID_NOT_EMPTY";
    String NAME_NOT_EMPTY_MSG = "名称不能为空";
    String NAME_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.NAME_NOT_EMPTY";
    String SORT_NOT_EMPTY_MSG = "排序不能为空";
    String SORT_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.SORT_NOT_EMPTY";
    String TYPE_NOT_EMPTY_MSG = "类型不能为空";
    String TYPE_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.TYPE_NOT_EMPTY";
    String HIDE_NOT_EMPTY_MSG = "是否隐藏不能为空";
    String HIDE_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.HIDE_NOT_EMPTY";
    String PASSWORD_NOT_EMPTY_MSG = "密码不能为空";
    String PASSWORD_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.PASSWORD_NOT_EMPTY";
    String ID_NOT_EMPTY_MSG = "id不能为空";
    String ID_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.ID_NOT_EMPTY";
    String IDS_NOT_EMPTY_MSG = "ids不能为空";
    String IDS_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.IDS_NOT_EMPTY";
    String OLD_PASSWORD_NOT_EMPTY_MSG = "旧密码不能为空";
    String OLD_PASSWORD_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.OLD_PASSWORD_NOT_EMPTY";
    String NEW_PASSWORD_NOT_EMPTY_MSG = "新密码不能为空";
    String NEW_PASSWORD_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.NEW_PASSWORD_NOT_EMPTY";
    String RE_PASSWORD_NOT_EMPTY_MSG = "确认密码不能为空";
    String RE_PASSWORD_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.RE_PASSWORD_NOT_EMPTY";
    String LAST_MODIFY_TIME_NOT_EMPTY_MSG = "最后修改时间(乐观锁)不能为空";
    String LAST_MODIFY_TIME_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.LAST_MODIFY_TIME_NOT_EMPTY";
    String SCAN_QR_CODE_FLAG_NOT_EMPTY_MSG = "二维码登录标识不能为空";
    String SCAN_QR_CODE_FLAG_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.SCAN_QR_CODE_FLAG_NOT_EMPTY";
    String SCAN_LOGIN_ID_NOT_EMPTY_MSG = "登录id不能为空";
    String SCAN_LOGIN_ID_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.SCAN_LOGIN_ID_NOT_EMPTY";
    String SCAN_LOGIN_KEY_NOT_EMPTY_MSG = "loginKey不能为空";
    String SCAN_LOGIN_KEY_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.SCAN_LOGIN_ID_NOT_EMPTY";
    String STATUS_NOT_EMPTY_MSG = "状态不能为空";
    String STATUS_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.STATUS_NOT_EMPTY";
    String USER_ID_NOT_EMPTY_MSG = "人员ID不能为空";
    String USER_ID_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.USER_ID_NOT_EMPTY";
    String ROLE_ID_NOT_EMPTY_MSG = "角色ID不能为空";
    String ROLE_ID_NOT_EMPTY_I18N_KEY = "MX.VALIDATE.SECURITY.ROLE_ID_NOT_EMPTY";
}
