/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.ymate.netty.impl;

import cn.hutool.core.util.ObjectUtil;
import com.mx.ymate.netty.INetty;
import com.mx.ymate.netty.INettyConfig;
import com.mx.ymate.netty.annotation.NettyConf;
import io.netty.channel.ChannelInboundHandlerAdapter;
import net.ymate.platform.commons.util.ClassUtils;
import net.ymate.platform.core.configuration.IConfigReader;
import net.ymate.platform.core.module.IModuleConfigurer;
import org.apache.commons.lang3.StringUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * DefaultNettyConfig generated By ModuleMojo on 2022/07/07 10:19
 *
 * @author YMP (https://www.ymate.net/)
 */
public final class DefaultNettyConfig implements INettyConfig {

    private boolean enabled = true;
    private String client = "all";
    private int serverPort;
    private int serverStartPort;
    private int serverEndPort;
    private int serverHeartBeatTime;
    private List<String> serverExcludePort = new ArrayList<>();
    private List<ChannelInboundHandlerAdapter> serverHandler = new ArrayList<>();
    private ChannelInboundHandlerAdapter serverDecoder;
    private List<String> clientRemoteAddress = new ArrayList<>();
    private int clientHeartBeatTime;
    private List<ChannelInboundHandlerAdapter> clientHandler = new ArrayList<>();
    private ChannelInboundHandlerAdapter clientDecoder;

    private boolean initialized;

    private String serverDecoderClassName;
    private String clientDecoderClassName;


    public static DefaultNettyConfig defaultConfig() {
        return builder().build();
    }

    public static DefaultNettyConfig create(IModuleConfigurer moduleConfigurer) {
        return new DefaultNettyConfig(null, moduleConfigurer);
    }

    public static DefaultNettyConfig create(Class<?> mainClass, IModuleConfigurer moduleConfigurer) {
        return new DefaultNettyConfig(mainClass, moduleConfigurer);
    }

    public static Builder builder() {
        return new Builder();
    }

    private DefaultNettyConfig() {
    }

    private DefaultNettyConfig(Class<?> mainClass, IModuleConfigurer moduleConfigurer) {
        IConfigReader configReader = moduleConfigurer.getConfigReader();
        //
        NettyConf confAnn = mainClass == null ? null : mainClass.getAnnotation(NettyConf.class);
        //
        enabled = configReader.getBoolean(ENABLED, confAnn == null || confAnn.enabled());
        client = configReader.getString(CLIENT, confAnn != null ? confAnn.client() : client);
        serverPort = configReader.getInt(SERVER_PORT, confAnn != null ? confAnn.serverPort() : serverPort);
        serverStartPort = configReader.getInt(SERVER_START_PORT, confAnn != null ? confAnn.serverStartPort() : serverStartPort);
        serverEndPort = configReader.getInt(SERVER_END_PORT, confAnn != null ? confAnn.serverEndPort() : serverEndPort);
        serverHeartBeatTime = configReader.getInt(SERVER_HEART_BEAT_TIME, confAnn != null ? confAnn.serverHeartBeatTime() : serverHeartBeatTime);
        serverExcludePort = ObjectUtil.defaultIfNull(configReader.getList(SERVER_EXCLUDE_PORT), serverExcludePort);
        List<String> serverHandlerClassNameList = ObjectUtil.defaultIfNull(configReader.getList(SERVER_HANDLER_CLASS), new ArrayList<>());
        if (!serverHandlerClassNameList.isEmpty()) {
            for (String className : serverHandlerClassNameList) {
                serverHandler.add(ClassUtils.impl(className, ChannelInboundHandlerAdapter.class, this.getClass()));
            }
        }

         serverDecoderClassName = configReader.getString(SERVER_DECODER_CLASS);

        clientRemoteAddress = ObjectUtil.defaultIfNull(configReader.getList(CLIENT_REMOTE_ADDRESS), clientRemoteAddress);
        clientHeartBeatTime = configReader.getInt(CLIENT_HEART_BEAT_TIME, confAnn != null ? confAnn.clientHeartBeatTime() : clientHeartBeatTime);

        List<String> clientHandlerClassNameList = ObjectUtil.defaultIfNull(configReader.getList(CLIENT_HANDLER_CLASS), new ArrayList<>());
        if (!clientHandlerClassNameList.isEmpty()) {
            for (String className : clientHandlerClassNameList) {
                clientHandler.add(ClassUtils.impl(className, ChannelInboundHandlerAdapter.class, this.getClass()));
            }
        }
        clientDecoderClassName = configReader.getString(CLIENT_DECODER_CLASS);

    }

    @Override
    public void initialize(INetty owner) throws Exception {
        if (!initialized) {
            if (enabled) {
                // TODO What to do?
            }
            initialized = true;
        }
    }

    @Override
    public boolean isInitialized() {
        return initialized;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    @Override
    public String client() {
        return client;
    }

    @Override
    public Integer serverPort() {
        return serverPort;
    }

    @Override
    public Integer serverStartPort() {
        return serverStartPort;
    }

    @Override
    public Integer serverEndPort() {
        return serverEndPort;
    }

    @Override
    public Integer serverHeartBeatTime() {
        return serverHeartBeatTime;
    }

    @Override
    public List<String> serverExcludePort() {
        return serverExcludePort;
    }

    @Override
    public List<ChannelInboundHandlerAdapter> serverHandler() {
        return serverHandler;
    }

    @Override
    public ChannelInboundHandlerAdapter serverDecoder() {
        if (StringUtils.isNotBlank(serverDecoderClassName)) {
            serverDecoder = ClassUtils.impl(serverDecoderClassName, ChannelInboundHandlerAdapter.class, this.getClass());
        }

        return serverDecoder;
    }

    @Override
    public List<String> clientRemoteAddress() {
        return clientRemoteAddress;
    }

    @Override
    public Integer clientHeartBeatTime() {
        return clientHeartBeatTime;
    }

    @Override
    public List<ChannelInboundHandlerAdapter> clientHandler() {
        return clientHandler;
    }

    @Override
    public ChannelInboundHandlerAdapter clientDecoder() {
        if (StringUtils.isNotBlank(clientDecoderClassName)) {
            clientDecoder = ClassUtils.impl(clientDecoderClassName, ChannelInboundHandlerAdapter.class, this.getClass());
        }
        return clientDecoder;
    }

    public void setEnabled(boolean enabled) {
        if (!initialized) {
            this.enabled = enabled;
        }
    }

    public void setClient(String client) {
        if (!initialized) {
            this.client = client;
        }
    }

    public void setServerPort(Integer serverPort) {
        if (!initialized) {
            this.serverPort = serverPort;
        }
    }

    public void setServerStartPort(Integer serverStartPort) {
        if (!initialized) {
            this.serverStartPort = serverStartPort;
        }
    }

    public void setServerEndPort(Integer serverEndPort) {
        if (!initialized) {
            this.serverEndPort = serverEndPort;
        }
    }

    public void setServerHeartBeatTime(Integer serverHeartBeatTime) {
        if (!initialized) {
            this.serverHeartBeatTime = serverHeartBeatTime;
        }
    }

    public void setServerExcludePort(List<String> serverExcludePort) {
        if (!initialized) {
            this.serverExcludePort = serverExcludePort;
        }
    }

    public void setServerHandlerClass(List<ChannelInboundHandlerAdapter> serverHandler) {
        if (!initialized) {
            this.serverHandler = serverHandler;
        }
    }

    public void setServerDecoderClass(ChannelInboundHandlerAdapter serverDecoder) {
        if (!initialized) {
            this.serverDecoder = serverDecoder;
        }
    }

    public void setClientRemoteAddress(List<String> clientRemoteAddress) {
        if (!initialized) {
            this.clientRemoteAddress = clientRemoteAddress;
        }
    }

    public void setClientHeartBeatTime(Integer clientHeartBeatTime) {
        if (!initialized) {
            this.clientHeartBeatTime = clientHeartBeatTime;
        }
    }

    public void setClientHandlerClass(List<ChannelInboundHandlerAdapter> clientHandler) {
        if (!initialized) {
            this.clientHandler = clientHandler;
        }
    }

    public void setClientDecoderClass(ChannelInboundHandlerAdapter clientDecoder) {
        if (!initialized) {
            this.clientDecoder = clientDecoder;
        }
    }


    public static final class Builder {

        private final DefaultNettyConfig config = new DefaultNettyConfig();

        private Builder() {
        }

        public Builder enabled(boolean enabled) {
            config.setEnabled(enabled);
            return this;
        }

        public Builder client(String client) {
            config.setClient(client);
            return this;
        }

        public Builder serverPort(Integer serverPort) {
            config.setServerPort(serverPort);
            return this;
        }

        public Builder serverStartPort(Integer serverStartPort) {
            config.setServerStartPort(serverStartPort);
            return this;
        }

        public Builder serverEndPort(Integer serverEndPort) {
            config.setServerEndPort(serverEndPort);
            return this;
        }

        public Builder serverHeartBeatTime(Integer serverHeartBeatTime) {
            config.setServerHeartBeatTime(serverHeartBeatTime);
            return this;
        }

        public Builder serverExcludePort(List<String> serverExcludePort) {
            config.setServerExcludePort(serverExcludePort);
            return this;
        }

        public Builder serverHandlerClass(List<ChannelInboundHandlerAdapter> serverHandlerClass) {
            config.setServerHandlerClass(serverHandlerClass);
            return this;
        }

        public Builder serverDecoderClass(ChannelInboundHandlerAdapter serverDecoderClass) {
            config.setServerDecoderClass(serverDecoderClass);
            return this;
        }


        public Builder clientRemoteAddress(List<String> clientRemoteAddress) {
            config.setClientRemoteAddress(clientRemoteAddress);
            return this;
        }

        public Builder clientHeartBeatTime(Integer clientHeartBeatTime) {
            config.setClientHeartBeatTime(clientHeartBeatTime);
            return this;
        }

        public Builder clientHandlerClass(List<ChannelInboundHandlerAdapter> clientHandlerClass) {
            config.setClientHandlerClass(clientHandlerClass);
            return this;
        }

        public Builder clientDecoderClass(ChannelInboundHandlerAdapter clientDecoderClass) {
            config.setClientDecoderClass(clientDecoderClass);
            return this;
        }

        public DefaultNettyConfig build() {
            return config;
        }
    }
}