/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.ymate.monitor;

import com.mx.ymate.monitor.mq.IDataSubscribeListener;
import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IInitialization;

/**
 * INettyConfig generated By ModuleMojo on 2022/07/07 10:19
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IMonitorConfig extends IInitialization<IMonitor> {

    String ENABLED = "enabled";
    String TIME = "time";
    String CLIENT = "client";
    String AUTO_START = "autoStart";
    String SERVER_ID = "serverId";
    String PROJECT_ID = "projectId";
    String DATA_SUBSCRIBE_LISTENER = "dataSubscribeListener";

    /**
     * 模块是否已启用, 默认值: true
     *
     * @return 返回false表示禁用
     */
    boolean isEnabled();

    /**
     * 是否自动启动
     *
     * @return
     */
    Boolean autoStart();

    /**
     * 客户端类型 默认all  可选值 all|client|server
     */
    String client();

    /**
     * 上报周期 单位秒 默认30秒
     *
     * @return
     */
    Integer time();


    /**
     * 服务器id
     */
    String serverId();

    /**
     * 项目id
     */
    String projectId();

    /**
     * 数据订阅类
     *
     * @return
     */
    IDataSubscribeListener dataSubscribeListener();
}