package com.mx.ymate.security.base.code;

import com.mx.ymate.dev.code.II18nCode;

/**
 * @Author: mengxiang.
 * @Date 2025/04/24.
 * @Time: 11:00.
 * @Description:
 */
public enum SecurityCode implements II18nCode {

    /**
     * 安全错误码 70开头
     */
    SECURITY_CHECK_ERROR("MS000", "MX.CODE.SECURITY.SEND_ERROR", "检查错误"),
    SECURITY_LOGIN_USER_NAME_NOT_EXIST("MS001", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_NAME_NOT_EXIST", "用户名不存在"),
    SECURITY_LOGIN_USER_NAME_OR_PASSWORD_ERROR("MS002", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_NAME_OR_PASSWORD_ERROR", "用户名或密码错误"),
    SECURITY_LOGIN_USER_LOCKED("MS003", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_LOCKED", "用户被锁住，请在{}后重试"),
    SECURITY_LOGIN_USER_DISABLE("MS004", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_DISABLE", "用户被禁用,请联系管理员!"),
    SECURITY_USER_PASSWORD_NOT_SAME("MS005", "MX.CODE.SECURITY.SECURITY_USER_PASSWORD_NOT_SAME", "两次密码输入不一致"),
    SECURITY_USER_OLD_PASSWORD_ERROR("MS006", "MX.CODE.SECURITY.SECURITY_USER_OLD_PASSWORD_ERROR", "原密码错误"),
    SECURITY_USER_NEW_PASSWORD_NOT_SAME_OLD_PASSWORD("MS007", "MX.CODE.SECURITY.SECURITY_USER_NEW_PASSWORD_NOT_SAME_OLD_PASSWORD", "新密码不能和原密码相同"),
    SECURITY_USER_ROLE_EXISTS("MS008", "MX.CODE.SECURITY.SECURITY_USER_ROLE_EXISTS", "该角色已经添加过了"),
    SECURITY_MENU_HAS_CHILD_NOT_DELETE("MS009", "MX.CODE.SECURITY.SECURITY_MENU_HAS_CHILD_NOT_DELETE", "有子菜单不能删除!"),
    SECURITY_MENU_ROLE_EXISTS("MS010", "MX.CODE.SECURITY.SECURITY_MENU_ROLE_EXISTS", "该角色已经添加过了!"),
    SECURITY_LOGIN_USER_LOCK_SCREEN("MS011", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_LOCK_SCREEN", "屏幕被锁定，请先解锁"),
    SECURITY_LOGIN_SCAN_QRCODE_EXPIRES_ERROR("MS012", "MX.CODE.SECURITY.SECURITY_LOGIN_SCAN_QRCODE_EXPIRES_ERROR", "请设置正确的二维码过期时间"),
    SECURITY_LOGIN_SCAN_QRCODE_CREATE_ERROR("MS013", "MX.CODE.SECURITY.SECURITY_LOGIN_SCAN_QRCODE_CREATE_ERROR", "二维码申请失败"),
    SECURITY_LOGIN_SCAN_QRCODE_TIMEOUT("MS014", "MX.CODE.SECURITY.SECURITY_LOGIN_SCAN_QRCODE_TIMEOUT", "二维码已失效"),
    SECURITY_LOGIN_SCAN_QRCODE_REPEAT("MS015", "MX.CODE.SECURITY.SECURITY_LOGIN_SCAN_QRCODE_REPEAT", "该二维码已经被扫描过，请勿重复扫码"),
    SECURITY_LOGIN_SCAN_QRCODE_NEED_SCAN("MS016", "MX.CODE.SECURITY.SECURITY_LOGIN_SCAN_QRCODE_NEED_SCAN", "请先扫码"),
    SECURITY_LOGIN_USER_NOT_EXIST("MS017", "MX.CODE.SECURITY.SECURITY_LOGIN_USER_NOT_EXIST", "用户不存在");


    private final String code;
    private final String i18nKey;
    private final String msg;

    SecurityCode(String code, String i18nKey, String msg) {
        this.code = code;
        this.i18nKey = i18nKey;
        this.msg = msg;
    }

    @Override
    public String code() {
        return code;
    }

    @Override
    public String i18nKey() {
        return i18nKey;
    }

    @Override
    public String msg() {
        return msg;
    }

}
