/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.ymate.netty.annotation;

import io.netty.channel.ChannelInboundHandlerAdapter;

import java.lang.annotation.*;

/**
 * NettyConf generated By ModuleMojo on 2022/07/07 10:19
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface NettyConf {

    /**
     * @return 模块是否已启用, 默认值: true
     */
    boolean enabled() default true;

    /**
     * #启动的客户端 all全部 server服务端  client 客户端  默认all
     *
     * @return
     */
    String client() default "all";

    /**
     * 服务端端口 优先级最高
     */
    int serverPort();

    /**
     * 服务端开始端口 指定port了 以port为准
     */
    int serverStartPort();

    /**
     * 服务端结束端口 指定port了 以port为准
     */
    int serverEndPort();

    /**
     * 心跳维护时间 默认不维护
     */
    int serverHeartBeatTime();

    /**
     * 心跳维护时间 默认不维护
     */
    int clientHeartBeatTime();

}
