#-------------------------------------
# module.netty \u6A21\u5757\u521D\u59CB\u5316\u53C2\u6570
#-------------------------------------

# \u6A21\u5757\u662F\u5426\u5DF2\u542F\u7528, \u9ED8\u8BA4\u503C: true
ymp.configs.module.netty.enabled=false
#-------------------------------------
# \u670D\u52A1\u7AEF\u914D\u7F6E
#-------------------------------------
#\u670D\u52A1\u7AEF\u540D\u79F0 \u53EF\u4EE5\u6307\u5B9A\u591A\u4E2A \u9ED8\u8BA4default
ymp.configs.module.netty.server.name=
#\u670D\u52A1\u7AEF\u662F\u5426\u81EA\u52A8\u521D\u59CB\u5316 \u9ED8\u8BA4false
ymp.configs.module.netty.server.autoInit=false
#\u670D\u52A1\u5730\u5740 \u9ED8\u8BA4127.0.0.1
ymp.configs.module.netty.server.default.host=
#\u670D\u52A1\u7AEF\u7AEF\u53E3
ymp.configs.module.netty.server.default.port=
#\u5FC3\u8DF3\u7EF4\u62A4\u65F6\u95F4\uFF08\u4E09\u4E2A\u65F6\u95F4\uFF09\u683C\u5F0F\uFF1A\u8BFB\u7A7A\u95F2|\u5199\u7A7A\u95F2|\u8BFB\u5199\u7A7A\u95F2 \u9ED8\u8BA4\u7A7A\u4E0D\u7EF4\u62A4 \u5355\u4F4Ds
ymp.configs.module.netty.server.default.heartBeatTime=
# \u5FC3\u8DF3\u5B9E\u73B0\u7C7B \u5F53heartBeatTime\u4E0D\u7B49\u4E8E0\u7684\u65F6\u5019\u6709\u6548 \u7EE7\u627Fcom.mx.ymate.netty.heart.AbstractHeartBeatHandler\u7C7B
ymp.configs.module.netty.server.default.heartBeatClass=
#\u5904\u7406\u5668\u5305\u540D  \u591A\u4E2A\u7528|\u5206\u5272
ymp.configs.module.netty.server.default.handlerPackage=
# handler\u6CE8\u518C\u5668\u5668 \u4F1A\u548C\u81EA\u52A8\u7684\u5408\u5E76 \u4E3B\u8981\u7528\u6237netty\u81EA\u5E26\u7684 \u65E0\u6CD5\u6DFB\u52A0NettyHandlerDefine\u6CE8\u89E3\u7684\u7C7B
ymp.configs.module.netty.server.default.handlerRegistrarClass=
# option\u914D\u7F6E\u5668 \u5206\u4E3Aoption\u548CchildOption \u5B9E\u73B0com.mx.ymate.netty.option.IServerOptionConfig \u63A5\u53E3
ymp.configs.module.netty.server.default.optionConfigClass=

#-------------------------------------
# \u5BA2\u6237\u7AEF\u914D\u7F6E
#-------------------------------------
#\u5BA2\u6237\u7AEF\u540D\u79F0 \u53EF\u4EE5\u6307\u5B9A\u591A\u4E2A \u9ED8\u8BA4default
ymp.configs.module.netty.client.name=
#\u5BA2\u6237\u7AEF\u662F\u5426\u81EA\u52A8\u521D\u59CB\u5316 \u9ED8\u8BA4false
ymp.configs.module.netty.client.autoInit=false
#\u7B2C\u4E00\u6B21\u8FDE\u63A5\u5931\u8D25\u7684\u91CD\u8BD5\u65F6\u95F4\u95F4\u9694\uFF08\u79D2\uFF09\u9ED8\u8BA410s  \u5C0F\u4E8E\u7B49\u4E8E0\u4EE3\u8868\u4E0D\u91CD\u8FDE
ymp.configs.module.netty.client.default.initialRetryDelay=
#\u8FDC\u7A0B\u8FDE\u63A5\u5730\u5740 ip:port  \u591A\u4E2A\u7528|\u5206\u5272
ymp.configs.module.netty.client.default.remoteAddress=
# \u662F\u5426\u5F00\u542F\u65AD\u7EBF\u91CD\u8FDE \u9ED8\u8BA4false
ymp.configs.module.netty.client.default.reconnect.enabled=
# \u6700\u5927\u91CD\u8FDE\u6B21\u6570  \u9ED8\u8BA43 \u5C0F\u4E8E\u7B49\u4E8E0\u4EE3\u8868\u65E0\u9650\u6B21
ymp.configs.module.netty.client.default.reconnect.maxAttempts=
# \u91CD\u8FDE\u95F4\u9694 \u9ED8\u8BA410s  \u5C0F\u4E8E\u7B49\u4E8E0\u4EE3\u8868\u4E0D\u91CD\u8FDE
ymp.configs.module.netty.client.default.reconnect.interval=
# \u662F\u5426\u6307\u6570\u9000\u907F \u9ED8\u8BA4false \u6BCF\u6B21\u8FDE\u63A5\u5931\u8D25\u540E\uFF0C\u91CD\u8BD5\u65F6\u95F4\u95F4\u9694\u6307\u6570\u7EA7\u589E\u957F\uFF08\u4F8B\u5982\uFF1A1s \u2192 2s \u2192 4s \u2192 8s ...\uFF09\uFF0C\u6700\u591A\u5230\u67D0\u4E2A\u4E0A\u9650\u3002
ymp.configs.module.netty.client.default.reconnect.backoff=
# \u662F\u5426\u8FDE\u63A5\u6210\u529F\u540E\u91CD\u7F6E backoff \u9ED8\u8BA4true
ymp.configs.module.netty.client.default.reconnect.resetOnSuccess=
#\u5FC3\u8DF3\u7EF4\u62A4\u65F6\u95F4\uFF08\u4E09\u4E2A\u65F6\u95F4\uFF09\u683C\u5F0F\uFF1A\u8BFB\u7A7A\u95F2|\u5199\u7A7A\u95F2|\u8BFB\u5199\u7A7A\u95F2 \u9ED8\u8BA4\u7A7A\u4E0D\u7EF4\u62A4 \u5355\u4F4Ds
ymp.configs.module.netty.client.default.heartBeatTime=
# \u5FC3\u8DF3\u5B9E\u73B0\u7C7B \u5F53heartBeatTime\u4E0D\u7B49\u4E8E0\u7684\u65F6\u5019\u6709\u6548 \u7EE7\u627Fcom.mx.ymate.netty.heart.AbstractHeartBeatHandler\u7C7B
ymp.configs.module.netty.client.default.heartBeatClass=
#\u5904\u7406\u5668\u5305\u540D  \u591A\u4E2A\u7528|\u5206\u5272
ymp.configs.module.netty.client.default.handlerPackage=
# handler\u6CE8\u518C\u5668\u5668 \u4F1A\u548C\u81EA\u52A8\u7684\u5408\u5E76 \u4E3B\u8981\u7528\u6237netty\u81EA\u5E26\u7684 \u65E0\u6CD5\u6DFB\u52A0NettyHandlerDefine\u6CE8\u89E3\u7684\u7C7B
ymp.configs.module.netty.client.default.handlerRegistrarClass=
# option\u914D\u7F6E\u5668  \u5B9E\u73B0com.mx.ymate.netty.option.IClientOptionConfig \u63A5\u53E3
ymp.configs.module.netty.client.default.optionConfigClass=

#-------------------------------------
# websocket\u914D\u7F6E
#-------------------------------------
#websocket\u662F\u5426\u81EA\u52A8\u521D\u59CB\u5316 \u9ED8\u8BA4false
ymp.configs.module.netty.websocket.autoInit=false
#websocket\u7AEF\u53E3 \u9ED8\u8BA48756
ymp.configs.module.netty.websocket.port=
#\u5FC3\u8DF3\u7EF4\u62A4\u65F6\u95F4\uFF08\u4E09\u4E2A\u65F6\u95F4\uFF09\u683C\u5F0F\uFF1A\u8BFB\u7A7A\u95F2|\u5199\u7A7A\u95F2|\u8BFB\u5199\u7A7A\u95F2 \u9ED8\u8BA4\u7A7A\u4E0D\u7EF4\u62A4 \u5355\u4F4Ds
ymp.configs.module.netty.websocket.heartBeatTime=
# \u5FC3\u8DF3\u5B9E\u73B0\u7C7B \u5F53heartBeatTime\u4E0D\u7B49\u4E8E0\u7684\u65F6\u5019\u6709\u6548 \u7EE7\u627Fcom.mx.ymate.netty.heart.AbstractHeartBeatHandler\u7C7B
ymp.configs.module.netty.websocket.heartBeatClass=
#websocket\u8BF7\u6C42\u8DEF\u5F84\u524D\u7F00 \u9ED8\u8BA4/name/websocket
ymp.configs.module.netty.websocket.mapping=
#websocket \u5904\u7406\u5668\u6240\u5728\u5305 \u591A\u4E2A\u7528|\u5206\u5272
ymp.configs.module.netty.websocket.handlerPackage=
# option\u914D\u7F6E\u5668 \u5206\u4E3Aoption\u548CchildOption \u5B9E\u73B0com.mx.ymate.netty.option.IWebsocketOptionConfig \u63A5\u53E3
ymp.configs.module.netty.websocket.optionConfigClass=