/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.ymate.satoken.annotation;

import java.lang.annotation.*;

/**
 * SaTokenConf generated By ModuleMojo on 2022/07/03 12:39
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface SaTokenConf {

    /**
     * @return 模块是否已启用, 默认值: true
     */
    boolean enabled() default true;

    /**
     * token名称 (同时也是cookie名称)
     *
     * @return
     */
    String tokenName() default "satoken";

    /**
     * token的长久有效期(单位:秒) 默认30天, -1代表永久
     *
     * @return
     */
    long timeout() default 60 * 60 * 24 * 30;

    /**
     * token临时有效期 [指定时间内无操作就视为token过期] (单位: 秒), 默认-1 代表不限制
     * (例如可以设置为1800代表30分钟内无操作就过期)
     */
    long activityTimeout() default -1;

    /**
     * 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
     */
    boolean isConcurrent() default true;

    /**
     * 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
     */
    boolean isShare() default true;

    /**
     * 同一账号最大登录数量，-1代表不限 （只有在 isConcurrent=true, isShare=false 时此配置才有效）
     */
    int maxLoginCount() default 12;

    /**
     * 是否尝试从请求体里读取token
     */
    boolean isReadBody() default true;

    /**
     * 是否尝试从header里读取token
     */
    boolean isReadHead() default true;

    /**
     * 是否尝试从cookie里读取token
     */
    boolean isReadCookie() default true;

    /**
     * token风格(默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik)
     */
    String tokenStyle() default "uuid";

    /**
     * 默认dao层实现类中，每次清理过期数据间隔的时间 (单位: 秒) ，默认值30秒，设置为-1代表不启动定时清理
     */
    int dataRefreshPeriod() default 30;

    /**
     * 获取[token专属session]时是否必须登录 (如果配置为true，会在每次获取[token-session]时校验是否登录)
     */
    boolean tokenSessionCheckLogin() default true;

    /**
     * 是否打开自动续签 (如果此值为true, 框架会在每次直接或间接调用getLoginId()时进行一次过期检查与续签操作)
     */
    boolean autoRenew() default true;

    /**
     * token前缀, 格式样例(satoken: Bearer xxxx-xxxx-xxxx-xxxx)
     */
    String tokenPrefix();

    /**
     * 是否在初始化配置时打印版本字符画
     */
    boolean isPrint() default true;

    /**
     * 是否打印操作日志
     */
    boolean isLog() default true;

    /**
     * jwt秘钥 (只有集成 jwt 模块时此参数才会生效)
     */
    String jwtSecretKey();

    /**
     * Id-Token的有效期 (单位: 秒)
     */
    long idTokenTimeout() default 60 * 60 * 24;

    /**
     * Http Basic 认证的账号和密码
     */
    String basic() default "";

    /**
     * 配置当前项目的网络访问地址
     *
     * @return
     */
    String currDomain();

    /**
     * 是否校验Id-Token（部分rpc插件有效
     *
     * @return
     */
    boolean checkIdToken() default false;

    /**
     * 域（写入Cookie时显式指定的作用域, 常用于单点登录二级域名共享Cookie的场景）
     */
    String cookieDomain();

    /**
     * 路径
     */
    String cookiePath();

    /**
     * 是否只在 https 协议下有效
     */
    boolean cookieSecure() default false;

    /**
     * 是否禁止 js 操作 Cookie
     */
    boolean cookieHttpOnly() default false;

    /**
     * 第三方限制级别（Strict=完全禁止，Lax=部分允许，None=不限制）
     */
    String cookieSameSite();
}
