/*
 * Copyright 2022 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.ymate.security.annotation;

import com.mx.ymate.security.handler.ILoginHandler;
import com.mx.ymate.security.handler.IUserHandler;

import java.lang.annotation.*;

/**
 * SaTokenConf generated By ModuleMojo on 2022/07/03 12:39
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface SecurityConf {

    /**
     * @return 模块是否已启用, 默认值: true
     */
    boolean enabled() default true;

    /**
     * 客户端名称
     *
     * @return
     */
    String client() default "default";

    /**
     * loginHandler实现类
     *
     * @return
     */
    Class<? extends ILoginHandler> loginHandlerClass() default ILoginHandler.DefaultLoginHandler.class;

    /**
     * userHandler实现类
     *
     * @return
     */
    Class<? extends IUserHandler> userHandlerClass() default IUserHandler.DefaultUserHandler.class;


    /**
     * 验证错误N次后锁定账户  默认不锁定  -1不锁定
     */
    int errorCount() default -1;

    /**
     * 是否开启日志记录 默认false
     */
    boolean openLog() default false;


    /**
     * 登录拦截排除的路径用|分割
     */
    String excludePathPatterns() default "";

}
